/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
sum_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Proceso de SUMA\n");
	result = argp->num1+argp->num2;
	printf("Solicitud: SUMAR %d + %d\n", argp->num1, argp->num2);
	printf("El resultado es: %d\n", result);

	return &result;
}

int *
res_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Proceso de RESTA\n");
	result = argp->num1-argp->num2;
	printf("Solicitud: RESTAR %d - %d\n", argp->num1, argp->num2);
	printf("El resultado es: %d\n", result);

	return &result;
}

int *
mul_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Proceso de MULTIPLICACION\n");
	result = argp->num1*argp->num2;
	printf("Solicitud: MULTIPLICAR %d * %d\n", argp->num1, argp->num2);
	printf("El resultado es: %d\n", result);

	return &result;
}

int *
div_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Proceso de DIVISION\n");
	result = argp->num1/argp->num2;
	printf("Solicitud: DIVIDIR %d / %d\n", argp->num1, argp->num2);
	printf("El resultado es: %d\n", result);

	return &result;
}
