/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


int
calculadora_prog_1(char *host, int n1, int n2, int op, CLIENT *clnt)
{
	int  *result_1;
	inputs  sum_1_arg;
	int  *result_2;
	inputs  res_1_arg;
	int  *result_3;
	inputs  mul_1_arg;
	int  *result_4;
	inputs  div_1_arg;

	if(op == 1){
		sum_1_arg.num1 = n1;
		sum_1_arg.num2 = n2;
		sum_1_arg.opcion = op;

		result_1 = sum_1(&sum_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_1;

	} else if(op == 2){
		res_1_arg.num1 = n1;
		res_1_arg.num2 = n2;
		res_1_arg.opcion = op;

		result_2 = res_1(&res_1_arg, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_2;

	} else if(op == 3){
		mul_1_arg.num1 = n1;
		mul_1_arg.num2 = n2;
		mul_1_arg.opcion = op;

		result_3 = mul_1(&mul_1_arg, clnt);
		if (result_3 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		return *result_3;

	}else if(op == 4){
		div_1_arg.num1 = n1;
		div_1_arg.num2 = n2;
		div_1_arg.opcion = op;

		if(n2 == 0){
			printf("La division entre cero no es valida\n");
			exit(0);
		} else {
			result_4 = div_1(&div_1_arg, clnt);
			if (result_4 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}

			return *result_4;
		}		
	} else{
		printf("Opcion no valida\n");
		return 0;
	}
}


int
main (int argc, char *argv[])
{
	char *host;
	int i, j, opc;
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	// Menu del programa
	printf("     ----------CALCULADORA RCP----------\n");
	printf("(1) Suma\n");
	printf("(2) Resta\n");
	printf("(3) Multiplicacion\n");
	printf("(4) Division\n");

	printf("Ingrese el primer numero: \n");
	scanf("%d", &i);

	printf("Ingrese el segundo numero: \n");
	scanf("%d", &j);

	printf("Ingrese la opcion a realizar (1-4)\n");
	scanf("%d", &opc);

	host = argv[1];

	clnt = clnt_create(host, CALCULADORA_PROG, CALCULADORA_VER, "udp");
	if(clnt == NULL){
		clnt_pcreateerror(host);
		exit(1);
	}
	
	printf("El resultado es = %d\n", calculadora_prog_1(host, i, j, opc, clnt));

	clnt_destroy(clnt);

	exit (0);
}
