/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int num1;
	int num2;
	int opcion;
};
typedef struct inputs inputs;

#define CALCULADORA_PROG 0x2fffffff
#define CALCULADORA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  int * sum_1(inputs *, CLIENT *);
extern  int * sum_1_svc(inputs *, struct svc_req *);
#define RES 2
extern  int * res_1(inputs *, CLIENT *);
extern  int * res_1_svc(inputs *, struct svc_req *);
#define MUL 3
extern  int * mul_1(inputs *, CLIENT *);
extern  int * mul_1_svc(inputs *, struct svc_req *);
#define DIV 4
extern  int * div_1(inputs *, CLIENT *);
extern  int * div_1_svc(inputs *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  int * sum_1();
extern  int * sum_1_svc();
#define RES 2
extern  int * res_1();
extern  int * res_1_svc();
#define MUL 3
extern  int * mul_1();
extern  int * mul_1_svc();
#define DIV 4
extern  int * div_1();
extern  int * div_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
